### ISSUE TITLE
Can you give me a contact number?

### ISSUE THREAD

**Issue by vae520283995** [cashuwallet/cashuwallet#2]
i don"t know how from mnemonic generate cardano address

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by raugfer** [comment]
@vae520283995 The wallet does this for you. It uses a non-standard scheme similar to what is commonly adopted for other crypto-currencies based on the ED25519 curve, such as Stellar:

There is just a single account sitting at the BIP32 Derivation Path m/44'/0'/0' (hardened-only) and adjustments are made to accomodate ED25519 key pair derivation from the BIP32 extended key pair.

These are the key files I suggest you to investigate in order to grasp the exact details:

[com/cashuwallet/android/crypto/Sync.java](https://github.com/cashuwallet/cashuwallet/blob/master/android/app/src/main/java/com/cashuwallet/android/crypto/Sync.java)
[com/raugfer/crypto/coins.java](https://github.com/raugfer/crypto-java/blob/74c8844181af84d7d57299c52d20ccfdaf30edd4/com/raugfer/crypto/coins.java)
[com/raugfer/crypto/hdwallet.java](https://github.com/raugfer/crypto-java/blob/74c8844181af84d7d57299c52d20ccfdaf30edd4/com/raugfer/crypto/hdwallet.java)

I will close the issue as this is not really a software problem but more of a support request.

Sorry for the late reply.
